Repository datwaft/bubbly.nvim, pull requests merged in 2020-12, with the labels that each got.

#6 Add branch bubble
  lua/bubbly/calculate.lua
  lua/bubbly/plugin.lua
  plugin/bubbly.vim
Labels: enhancement

#9 Bugfix: now there is check for if Syntastic is not installed
  lua/bubbly/plugin.lua
Labels: bug, complexity:low

#10 Fix check for if plugin function doesn't exist
  lua/bubbly/plugin.lua
Labels: bug, complexity:low

#11 Bugfix: fixed Signify bubble
  lua/bubbly/plugin.lua
Labels: complexity:low

#13 Visual block bugfix
  lua/bubbly/plugin.lua
Labels: bug, complexity:low

#18 Configurable version
  lua/bubbly/defaults.lua
  lua/bubbly/highlight.lua
  lua/bubbly/plugin.lua
  lua/bubbly/utils.lua
  plugin/bubbly.vim
  readme.md
Labels: complexity:medium, enhancement

#20 Bugfix: changing colorscheme clears highlights
  lua/bubbly/highlight.lua
Labels: bug, complexity:low

#23 Divide plugin in configurable modules
  lua/bubbly/components/branch.lua
  lua/bubbly/components/coc.lua
  lua/bubbly/components/filetype.lua
  lua/bubbly/components/mode.lua
  lua/bubbly/components/paste.lua
  lua/bubbly/components/path.lua
  lua/bubbly/components/progress.lua
  lua/bubbly/components/signify.lua
  lua/bubbly/defaults.lua
  lua/bubbly/factories/bubble.lua
  lua/bubbly/factories/statusline.lua
  lua/bubbly/plugin.lua
  lua/bubbly/utils.lua
Labels: complexity:medium, enhancement

#25 Updated documentation to accept components
  readme.md
Labels: documentation

#26 Enhancement: added branch symbol
  lua/bubbly/components/branch.lua
  lua/bubbly/defaults.lua
Labels: complexity:low, enhancement

#27 Bugfix: fixed branch bubble when no branch
  lua/bubbly/components/branch.lua
Labels: bug, complexity:low

#28 Add truncation point
  lua/bubbly/defaults.lua
  lua/bubbly/factories/statusline.lua
  readme.md
Labels: bug, enhancement

#34 Bugfix: fix to branch cd error message
  lua/bubbly/calculate.lua
Labels: bug, complexity:low

#35 Use `format` for when using symbols
  lua/bubbly/components/branch.lua
  lua/bubbly/components/coc.lua
  lua/bubbly/components/signify.lua
  lua/bubbly/defaults.lua
  readme.md
Labels: complexity:low, documentation, enhancement

#36 Tabline support
  lua/bubbly/defaults.lua
  lua/bubbly/factories/bubble.lua
  lua/bubbly/factories/tabline.lua
  plugin/bubbly.vim
  readme.md
Labels: complexity:medium, enhancement

#39 Rework of highlight and color configuration with foreground and background
  .luacheckrc
  lua/bubbly/defaults.lua
  lua/bubbly/factories/bubble.lua
  lua/bubbly/factories/highlight.lua
  lua/bubbly/factories/tabline.lua
  lua/bubbly/highlight.lua
  lua/bubbly/utils.lua
  readme.md
Labels: complexity:medium, documentation, enhancement

#40 Documentation: add truecolor warning
  readme.md
Labels: documentation

#41 Enhancement: better format for concatenation
  lua/bubbly/calculate.lua
  lua/bubbly/factories/bubble.lua
  lua/bubbly/factories/highlight.lua
  lua/bubbly/factories/statusline.lua
  lua/bubbly/factories/tabline.lua
  lua/bubbly/utils.lua
Labels: enhancement

#45 Use better ways to get current branch
  lua/bubbly/calculate.lua
Labels: complexity:low, enhancement

#44 Add builtin-lsp support
  lua/bubbly/calculate.lua
  lua/bubbly/components/builtinlsp/current_function.lua
  lua/bubbly/components/builtinlsp/diagnostic_count.lua
  lua/bubbly/defaults.lua
  lua/bubbly/utils.lua
  plugin/bubbly.vim
Labels: complexity:medium, enhancement

#46 Documentation: new built-in LSP bubbles documentation and code formatting
  lua/bubbly/calculate.lua
  lua/bubbly/components/builtinlsp/current_function.lua
  lua/bubbly/components/builtinlsp/diagnostic_count.lua
  lua/bubbly/defaults.lua
  lua/bubbly/utils.lua
  readme.md
Labels: complexity:low, documentation

#47 Warning if module in g:bubbly_statusline doesn't exists
  lua/bubbly/defaults.lua
  lua/bubbly/utils.lua
Labels: complexity:low, enhancement

#50 Add Option to Opt Out of Tabline
  lua/bubbly/defaults.lua
  plugin/bubbly.vim
Labels: complexity:low, enhancement
