Repository datwaft/bubbly.nvim, pull requests merged in 2021-01, with the labels that each got.

#52 Add .gitignore file
  .gitignore
Labels: enhancement

#54 Add tabline documentation
  lua/bubbly/defaults.lua
  plugin/bubbly.vim
  readme.md
Labels: documentation

#55 Reworked settings for modules and enabled configuration for inactive bubbles
  README.MD
  lua/bubbly/components/branch.lua
  lua/bubbly/components/builtinlsp/current_function.lua
  lua/bubbly/components/builtinlsp/diagnostic_count.lua
  lua/bubbly/components/coc.lua
  lua/bubbly/components/filetype.lua
  lua/bubbly/components/mode.lua
  lua/bubbly/components/paste.lua
  lua/bubbly/components/path.lua
  lua/bubbly/components/progress.lua
  lua/bubbly/components/signify.lua
  lua/bubbly/defaults.lua
  lua/bubbly/factories/bubble.lua
  lua/bubbly/factories/tabline.lua
Labels: complexity:medium, enhancement

#56 use a custom hi group instead of StatusLine
  lua/bubbly/factories/bubble.lua
  lua/bubbly/factories/highlight.lua
Labels: enhancement

#57 Documentation: fixed typo
  readme.md
Labels: bug, complexity:low, documentation

#59 Partially fixing git bubble on Windows
  lua/bubbly/calculate.lua
Labels: complexity:medium
