Repository datwaft/bubbly.nvim, pull requests merged in 2021-02, with the labels that each got.

#60 Typo
  lua/bubbly/components/progress.lua
  lua/bubbly/defaults.lua
  readme.md
Labels: bug, documentation

#63 [Typo] rowandol -> rowandcol
  lua/bubbly/defaults.lua
  readme.md
Labels: bug, complexity:low, documentation

#64 [Enhancement] Add configuration option for width
  lua/bubbly/components/progress.lua
  lua/bubbly/defaults.lua
  readme.md
Labels: complexity:low, enhancement

#66 Automate autocmds for bubbles
  lua/bubbly/autocommands/branch.lua
  lua/bubbly/autocommands/builtinlsp/current_function.lua
  lua/bubbly/calculate.lua
  lua/bubbly/components/branch.lua
  lua/bubbly/components/builtinlsp/current_function.lua
  lua/bubbly/factories/autocommands.lua
  plugin/bubbly.vim
Labels: complexity:medium, enhancement

#68 Rework readme.md
  readme.md
Labels: complexity:low, documentation

#70 Normalize headers
  lua/bubbly/components/branch.lua
  lua/bubbly/components/builtinlsp/current_function.lua
  lua/bubbly/components/builtinlsp/diagnostic_count.lua
  lua/bubbly/components/coc.lua
  lua/bubbly/components/filetype.lua
  lua/bubbly/components/mode.lua
  lua/bubbly/components/paste.lua
  lua/bubbly/components/path.lua
  lua/bubbly/components/progress.lua
  lua/bubbly/components/signify.lua
  lua/bubbly/defaults.lua
  lua/bubbly/factories/bubble.lua
  lua/bubbly/factories/highlight.lua
  lua/bubbly/factories/statusline.lua
  lua/bubbly/factories/tabline.lua
  lua/bubbly/highlight.lua
  lua/bubbly/plugin.lua
  lua/bubbly/utils.lua
  plugin/bubbly.vim
Labels: complexity:low, documentation

#71 Rework utils organization and IO
  lua/bubbly/autocommands/builtinlsp/current_function.lua
  lua/bubbly/components/branch.lua
  lua/bubbly/components/builtinlsp/current_function.lua
  lua/bubbly/components/builtinlsp/diagnostic_count.lua
  lua/bubbly/components/coc.lua
  lua/bubbly/components/filetype.lua
  lua/bubbly/components/mode.lua
  lua/bubbly/components/paste.lua
  lua/bubbly/components/path.lua
  lua/bubbly/components/progress.lua
  lua/bubbly/components/signify.lua
  lua/bubbly/core/module.lua
  lua/bubbly/defaults.lua
  lua/bubbly/factories/autocommands.lua
  lua/bubbly/factories/bubble.lua
  lua/bubbly/factories/highlight.lua
  lua/bubbly/factories/statusline.lua
  lua/bubbly/utils.lua
  lua/bubbly/utils/builtinlsp.lua
  lua/bubbly/utils/checkmodule.lua
  lua/bubbly/utils/highlight.lua
  lua/bubbly/utils/io.lua
  lua/bubbly/utils/prerequire.lua
  lua/bubbly/utils/string.lua
  lua/bubbly/utils/table.lua
  readme.md
Labels: complexity:high, enhancement

#73 Recompute highlights on VimEnter and ColorScheme events
  lua/bubbly/factories/highlight.lua
  plugin/bubbly.vim
Labels: complexity:medium, enhancement

#74 Changed g:bubbly_statusline default value
  lua/bubbly/defaults.lua
  readme.md
Labels: breaking, complexity:low, enhancement

#62 Initial draft commit to read the palette from the User1..9 highlight …
  lua/bubbly/factories/highlight.lua
  lua/bubbly/utils/highlight.lua
  readme.md
Labels: complexity:medium, enhancement

#75 More options for g:bubbly_palette (#62)
  lua/bubbly/factories/highlight.lua
  lua/bubbly/utils/highlight.lua
  readme.md
Labels: enhancement

#77 Rework statusline factory
  lua/bubbly/factories/statusline.lua
Labels: bug, complexity:medium, enhancement

#78 [Documentation] Minor fixes to readme.md
  readme.md
Labels: complexity:low, documentation

#80 [Documentation] Add aclaration for inactive style
  readme.md
Labels: documentation

#81 Add new component "buffers_number"
  lua/bubbly/components/buffers_number.lua
  lua/bubbly/defaults.lua
  readme.md
Labels: enhancement

#83 Merge `total_buffer_number` bubble
  lua/bubbly/components/total_buffer_number.lua
  lua/bubbly/defaults.lua
  readme.md
Labels: enhancement

#82 Add diagnostics from lsp-status plugin
  lua/bubbly/components/lsp_status/diagnostics.lua
  lua/bubbly/defaults.lua
  readme.md
Labels: enhancement

#85 Merge `lsp_status.diagnostics` bubble
  lua/bubbly/components/lsp_status/diagnostics.lua
  lua/bubbly/defaults.lua
  readme.md
Labels: enhancement

#84 Add messages component for lsp-status
  lua/bubbly/components/lsp_status/messages.lua
  lua/bubbly/defaults.lua
  readme.md
Labels: enhancement

#87 Fix lsp status messages
  lua/bubbly/components/lsp_status/diagnostics.lua
  lua/bubbly/components/lsp_status/messages.lua
Labels: enhancement

#86 Merge `lsp_status.messages` bubble
  lua/bubbly/components/lsp_status/diagnostics.lua
  lua/bubbly/components/lsp_status/messages.lua
  lua/bubbly/defaults.lua
  readme.md
Labels: enhancement

#91 [Enhancement] Better defaults for symbols
  lua/bubbly/defaults.lua
  readme.md
Labels: complexity:low, enhancement
