Repository datwaft/bubbly.nvim, pull requests merged in 2021-03, with the labels that each got.

#96 Feat: more configuration options
  lua/bubbly/defaults.lua
  lua/bubbly/factories/bubble.lua
  lua/bubbly/factories/statusline.lua
  readme.md
Labels: complexity:low, enhancement

#97 Minor refactor to plugin formatting
  lua/bubbly/autocommands/branch.lua
  lua/bubbly/autocommands/builtinlsp/current_function.lua
  lua/bubbly/components/branch.lua
  lua/bubbly/components/builtinlsp/current_function.lua
  lua/bubbly/components/builtinlsp/diagnostic_count.lua
  lua/bubbly/components/coc.lua
  lua/bubbly/components/filetype.lua
  lua/bubbly/components/lsp_status/diagnostics.lua
  lua/bubbly/components/lsp_status/messages.lua
  lua/bubbly/components/mode.lua
  lua/bubbly/components/paste.lua
  lua/bubbly/components/path.lua
  lua/bubbly/components/progress.lua
  lua/bubbly/components/signify.lua
  lua/bubbly/components/total_buffer_number.lua
  lua/bubbly/core/module.lua
  lua/bubbly/defaults.lua
  lua/bubbly/factories/autocommands.lua
  lua/bubbly/factories/bubble.lua
  lua/bubbly/factories/highlight.lua
  lua/bubbly/factories/statusline.lua
  lua/bubbly/factories/tabline.lua
  lua/bubbly/highlight.lua
  lua/bubbly/plugin.lua
  lua/bubbly/utils/builtinlsp.lua
  lua/bubbly/utils/checkmodule.lua
  lua/bubbly/utils/highlight.lua
  lua/bubbly/utils/io.lua
  lua/bubbly/utils/prerequire.lua
  lua/bubbly/utils/string.lua
  lua/bubbly/utils/table.lua
  readme.md
Labels: complexity:medium, documentation, enhancement

#98 Add blacklist capability to configuration
  lua/bubbly/components/branch.lua
  lua/bubbly/components/builtinlsp/current_function.lua
  lua/bubbly/components/builtinlsp/diagnostic_count.lua
  lua/bubbly/components/coc.lua
  lua/bubbly/components/filetype.lua
  lua/bubbly/components/lsp_status/diagnostics.lua
  lua/bubbly/components/lsp_status/messages.lua
  lua/bubbly/components/mode.lua
  lua/bubbly/components/paste.lua
  lua/bubbly/components/path.lua
  lua/bubbly/components/progress.lua
  lua/bubbly/components/signify.lua
  lua/bubbly/components/total_buffer_number.lua
  lua/bubbly/defaults.lua
  lua/bubbly/factories/tabline.lua
  lua/bubbly/utils/module.lua
  lua/bubbly/utils/string.lua
  readme.md
Labels: complexity:high, enhancement

#101 Add feature to color the closing character of the tabline bubbles
  lua/bubbly/defaults.lua
  lua/bubbly/factories/tabline.lua
  readme.md
Labels: complexity:low, enhancement

#102 Listen to FocusGained and VimResume
  lua/bubbly/autocommands/branch.lua
Labels: complexity:low, enhancement
